CREATE TABLE Thing(
	id      INTEGER PRIMARY KEY AUTOINCREMENT,
	name    TEXT UNIQUE NOT NULL
);

CREATE TABLE Recipe(
	id          INTEGER PRIMARY KEY AUTOINCREMENT,
	ingredient1 INTEGER NOT NULL,
	ingredient2 INTEGER NOT NULL,
	product     INTEGER NOT NULL,
	means       TEXT,
	was_first   INTEGER,
	FOREIGN KEY(ingredient1) REFERENCES Thing(id),
	FOREIGN KEY(ingredient2) REFERENCES Thing(id),
	FOREIGN KEY(product) REFERENCES Thing(id),
	UNIQUE(ingredient1, ingredient2)
);

CREATE TABLE Game(
	id		INTEGER PRIMARY KEY AUTOINCREMENT,
	gameid	TEXT UNIQUE NOT NULL
);

CREATE TABLE ThingInGame(
	id		INTEGER PRIMARY KEY AUTOINCREMENT,
	thing	INTEGER NOT NULL,
	game	INTEGER NOT NULL,
	FOREIGN KEY(thing) REFERENCES Thing(id),
	FOREIGN KEY(game) REFERENCES Game(id),
	UNIQUE(thing, game)
);
